### PR TITLE
adding GUSD-A kovan spell

### PR DESCRIPTION
**Pull request by hexonaut**
# Description

Spell Description: Adding GUSD-A spell

COB Team Name or Author(s): @hexonaut @godsflaw 

# Contribution Checklist

- [x] First commit title starts with COB Team Name and Collateral type (e.g. `___-TOKEN-X`)
- [ ] Code approved
- [x] Tests approved
- [ ] CI Tests pass

# Checklist

- [x] Every contract variable/method declared as public/external private/internal
- [x] Verify expiration (`4 days + 2 hours` monthly and `30 days` for the rest)
- [x] Verify hash in the description matches [here](https://emn178.github.io/online-tools/keccak_256.html)
- [x] Validate all addresses used are in Kovan changelog
- [x] Deploy spell to kovan `SOLC_FLAGS="--optimize --optimize-runs=1" dapp --use solc:0.5.12 build --extract && dapp create DssSpell --gas=5000000 --gas-price="$(seth --to-wei 3 "gwei")"`
- [x] Ensure contract is verified on `kovan` etherscan
- [x] Change test to use kovan spell address and deploy timestamp
- [x] Keep `Kovan-DssSpell.sol` and `Kovan-DssSpell.t.sol` the same, but make a copy in `archive`
- [ ] `squash and merge` this PR

### CODE REVIEW

**Comment by hexonaut** [comment]
Note: Tests are currently not working. Do not merge.

**Comment by hexonaut** [comment]
[PASS] testSpellIsCast() (gas: 4258359)
[PASS] testSpellIsCast_GUSD_INTEGRATION() (gas: 1924200)

**Comment by hexonaut** [comment]
Please note that I've had to comment out any lines in the tests that rely on the OSM, Medianizer and Flipper because it is a stablecoin and liquidations are turned off.

**Comment by godsflaw** [comment]
Had to fix up the GemJoin8 to put the implementation in the constructor, moved this PR over here to finish up:
https://github.com/makerdao/spells-kovan/pull/32

**Pull request closed without merging**
