### PR TITLE
SC-5261: Kovan Weekly Executive (Deploy LIQ-1.2)

### PR DESCRIPTION
**Pull request by lucas-manuel**

### CODE REVIEW

**Review by godsflaw — APPROVED** [review]

**Review by godsflaw — APPROVED** [review]
LGTM

**Review by wilbarnes — APPROVED** [review]
usdc-a/b and tusd-a liquidations are turned off and spell and test logic looks sound

**Review by kmbarry1 — APPROVED** [review]
LGTM

**Review by godsflaw — APPROVED** [review]
LGTM

**Pull request merged**
